spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    password: zxc06733
    url: jdbc:log4jdbc:mariadb://localhost:3306/habit
    username: habit
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true